services:
  - type: web
    name: dashboard-darkmode-system
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: FEATURE_DARK_MODE_ENABLED
        value: "false" # Ticket 1 por defecto
      - key: FEATURE_DARK_MODE_VISIBLE_ROLLOUT
        value: "10" # Ticket 2 al 10%
      - key: FEATURE_DARK_MODE_PERSISTENCE
        value: "true" # Ticket 3 activado
